[versions]
lombok = '9.0.0'
postgres = "42.7.3"
spring-boot = "4.0.1"

[libraries]
lombok = { module = 'org.projectlombok:lombok', version.ref = 'lombok' }
postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgres" }

[plugins]
spring-boot = { id = 'org.springframework.boot', version.ref = 'spring-boot' }
lombok = { id = 'io.freefair.lombok', version.ref = 'lombok' }
